# Generated by Django 5.1.1 on 2024-09-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField()),
                ('url', models.URLField()),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['method', 'url'], name='user_log_method_da185e_idx')],
            },
        ),
    ]
