# Generated by Django 5.1.1 on 2024-09-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('note', '0002_collaborator_notes_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='notes', to='label.label'),
        ),
    ]
